
export const FETCH_USER_COMPANIES = 'FETCH_USER_COMPANIES'
export const NEW_USER_COMPANY = 'NEW_USER_COMPANY'

export const FETCH_COMPANY_ESTIMATES = 'FETCH_COMPANY_ESTIMATES'
export const NEW_COMPANY_ESTIMATE = 'NEW_COMPANY_ESTIMATE'